# Generated by Django 5.0.7 on 2024-07-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio_app', '0002_project_github_project_view_live_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tools',
        ),
        migrations.AddField(
            model_name='project',
            name='tools',
            field=models.ManyToManyField(blank=True, null=True, to='portifolio_app.tools'),
        ),
    ]
